---
# tasks file for redmine_backlogs_ansible

- name: Fetch from git
  git:
    accept_hostkey: yes
    ssh_opts: -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
    repo: ssh://gitlab@git.forgeservicelab.fi:10022/forge_redmine-plugins/redmine_backlogs.git
    dest: "{{ redmine_dir }}"

- name: Migrate db
  command: bundle exec rake db:migrate
  args:
    chdir: "{{ redmine_dir }}"
  environment:
    RAILS_ENV: "{{ RAILS_ENV }}"
    sudo_user: "{{ sudo_user }}"

- name: Install
  command: bundle exec rake redmine:backlogs:install story_trackers="{{ redmine_backlogs.story_trackers }}" task_tracker="{{ redmine_backlogs.task_tracker }}"
  args:
    chdir: "{{ redmine_dir }}"
  environment:
    RAILS_ENV: "{{ RAILS_ENV }}"
    sudo_user: "{{ sudo_user }}"


